// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kdreqzyvypvkarbxoqqr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtkcmVxenl2eXB2a2FyYnhvcXFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2NjI2NzUsImV4cCI6MjA2NzIzODY3NX0.93osMmVC05n9usTZPxfTrJJN0Lnc1Rvvx-ej6r_XlEc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});